In [1]:
import torch
import random
import matplotlib.pyplot as plt
%matplotlib inline

# Fix random seeds
random.seed(42)
torch.manual_seed(42)
print("PyTorch version:", torch.__version__)

PyTorch version: 2.7.1+cu128


## 1.1 Tensor Creation

In [10]:
# Solution: create tensor x (1,2,3,4), float32 on CPU and print it
import torch
x = torch.arange(24, dtype=torch.float32, device='cpu').view(1,2,3,4)
print('x:', x)
print('shape:', x.shape, 'dtype:', x.dtype, 'device:', x.device)


x: tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],

         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]])
shape: torch.Size([1, 2, 3, 4]) dtype: torch.float32 device: cpu


In [11]:
# Solution: change dtype to long
x = x.to(dtype=torch.long)
print('x dtype changed to:', x.dtype)
print(x)


x dtype changed to: torch.int64
tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],

         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]])


In [12]:
# Solution: transpose to (1,2,4,3) by swapping the last two dims
x = torch.transpose(x, -1, -2)
print('shape after transpose:', x.shape)
print(x)


shape after transpose: torch.Size([1, 2, 4, 3])
tensor([[[[ 0,  4,  8],
          [ 1,  5,  9],
          [ 2,  6, 10],
          [ 3,  7, 11]],

         [[12, 16, 20],
          [13, 17, 21],
          [14, 18, 22],
          [15, 19, 23]]]])


In [13]:
# Solution: permute to (4,3,2,1) in one line
# current shape is (1,2,4,3); the order [2,3,1,0] yields sizes [4,3,2,1]
x = x.permute(2,3,1,0)
print('shape after permute:', x.shape)
print(x)


shape after permute: torch.Size([4, 3, 2, 1])
tensor([[[[ 0],
          [12]],

         [[ 4],
          [16]],

         [[ 8],
          [20]]],


        [[[ 1],
          [13]],

         [[ 5],
          [17]],

         [[ 9],
          [21]]],


        [[[ 2],
          [14]],

         [[ 6],
          [18]],

         [[10],
          [22]]],


        [[[ 3],
          [15]],

         [[ 7],
          [19]],

         [[11],
          [23]]]])


In [14]:
# Solution: view to (12, 2)
x = x.view(12, 2)
print('new size:', x.size())
print(x)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

## Tensor Indexing

In [15]:
# Tensor Indexing
# - Take the slice at index 1 on axis 0
# - Take all slices on axis 1 (:).
# - Take every other slice starting from index 1 on axis 2 (1::2).
import torch
y = torch.arange(24).view(2,3,4)
sel = y[1, :, 1::2]
print('y shape:', y.shape)
print('selected (y[1, :, 1::2]) shape:', sel.shape)
print(sel)


y shape: torch.Size([2, 3, 4])
selected (y[1, :, 1::2]) shape: torch.Size([3, 2])
tensor([[13, 15],
        [17, 19],
        [21, 23]])


## Tensor Arithmetics

In [16]:
# Solution: broadcasting with repeat/view/expand
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([10,20])

# repeat and reshape to (2,2)
z = y.repeat(2).view(2,2)
print('x:\n', x)
print('y:', y)
print('z (repeat->view to 2x2):\n', z)
print('x+z:\n', x+z)

# view to (2,1) and (1,2) for broadcasting
y_col = y.view(2,1)
y_row = y.view(1,2)
print('x + y_col (broadcast over columns):\n', x + y_col)
print('x + y_row (broadcast over rows):\n', x + y_row)

# do the above using expand (no data copy)
y_col_exp = y.view(2,1).expand(-1,2)
y_row_exp = y.view(1,2).expand(-1,2)
### Note: you may also use .expand_as(x)
print('x + y_col_exp:\n', x + y_col_exp)
print('x + y_row_exp:\n', x + y_row_exp)


x:
 tensor([[1, 2],
        [3, 4]])
y: tensor([10, 20])
z (repeat->view to 2x2):
 tensor([[10, 20],
        [10, 20]])
x+z:
 tensor([[11, 22],
        [13, 24]])
x + y_col (broadcast over columns):
 tensor([[11, 12],
        [23, 24]])
x + y_row (broadcast over rows):
 tensor([[11, 22],
        [13, 24]])
x + y_col_exp:
 tensor([[11, 12],
        [23, 24]])
x + y_row_exp:
 tensor([[11, 22],
        [13, 24]])
