In [2]:
import torch
import random
import matplotlib.pyplot as plt
%matplotlib inline

# Fix random seeds
random.seed(42)
torch.manual_seed(42)
print("PyTorch version:", torch.__version__)

PyTorch version: 2.7.1+cu128


## 1.1 Tensor Creation

In [ ]:
#TODO: Create a tensor x from the Python list [0,1,2,...,23] with size (1,2,3,4), data type float32 and device cpu
#TODO: Print this tensor



tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],

         [[12., 13., 14., 15.],
          [16., 17., 18., 19.],
          [20., 21., 22., 23.]]]])


In [ ]:
#TODO: Change the tensor data type to long
#TODO: Print x


tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],

         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]])


In [ ]:
#TODO: Use torch.transpose, change the size of x to (1,2,4,3). (swap only 2 axes)
#TODO: Print x


torch.Size([1, 2, 4, 3])
tensor([[[[ 0,  4,  8],
          [ 1,  5,  9],
          [ 2,  6, 10],
          [ 3,  7, 11]],

         [[12, 16, 20],
          [13, 17, 21],
          [14, 18, 22],
          [15, 19, 23]]]])


In [ ]:
#TODO: Use torch.permute, change the size of x to (4,3,2,1) **in one line**.
#TODO: Print x



torch.Size([2, 1, 3, 4]) tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]]],


        [[[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]])


In [ ]:
#TODO: Use torch.view, change the size of x to (12,2)
#TODO: Print the size of x
#TODO: Print x


torch.Size([12, 2])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])


## Tensor Indexing

In [ ]:
#TODO: Create a tensor y [0,1,2,...,23] using torch.arange, with data type float32 and device cpu. Change the size of y to (2,3,4)
#TODO: Create a single tensor by:
# - Take the slice at index 1 on axis 0
# - Take all slices on axis 1 (:).
# - Take every other slice starting from index 1 on axis 2 (1::2).
#TODO: Print this new tensor. Do not overwrite y.


y shape: torch.Size([2, 3, 4])
selected (y[1, :, 1::2]) shape: torch.Size([3, 2])
tensor([[13., 15.],
        [17., 19.],
        [21., 23.]])


In [ ]:
#TODO: Create an index tensor **idx** with value [3, 1].
#TODO: Use idx to get the 4th and 1st slices (in order) from the last axis of y
#TODO: Print this new tensor. Do not overwrite y.


y shape: torch.Size([2, 3, 4])
selected (y[:, :, idx]) shape: torch.Size([2, 3, 2])
tensor([[[ 3.,  1.],
         [ 7.,  5.],
         [11.,  9.]],

        [[15., 13.],
         [19., 17.],
         [23., 21.]]])


In [ ]:
#TODO: Create a tensor **coord** for coordinates [[0,1,2], [1,3,2]]
#TODO: Print torch.gather(y, coord)



torch.Size([2, 3, 4])
torch.Size([2, 3, 4])
tensor([[[0, 1, 2, 1],
         [3, 2, 0, 1],
         [2, 1, 3, 2]],

        [[0, 1, 2, 1],
         [3, 2, 0, 1],
         [2, 1, 3, 2]]])
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
tensor([[[ 0.,  1.,  2.,  1.],
         [ 7.,  6.,  4.,  5.],
         [10.,  9., 11., 10.]],

        [[12., 13., 14., 13.],
         [19., 18., 16., 17.],
         [22., 21., 23., 22.]]])


## Tensor Arithmetics

In [ ]:
#TODO: Create tensor x from list [[1,2],[3,4]] and tensor y from list [10,20]
#TODO: Create z by repeating y once, and resize it to size (2,2)
#TODO: Print x+z
#TODO: Create y_col_exp by viewing y as size (2,1) and print x+y_col_exp
#TODO: Create y_row_exp by viewing y as size (1,2) and print x+y_row_exp
#TODO: Do the above two operations with torch.expand
